[package]
name = "toolbox-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
toolbox-core = { path = "../core" }
