[package]
name = "toolbox-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
thiserror = "1.0.57"
